Tables
AIG-GAMING/Poker pull request #20
Opened 2022-08-15 07:54 UTC by Gulnazmd

2022-08-15 08:32 UTC, ionetek requested changes

2022-08-15 08:32 UTC, ionetek commented on src/features/components/header-menu/HeaderMenu.tsx
В проекте нужно использовать .svg они меньше весят и лучше отображаются на экранах с высоким разрешением.

2022-08-15 08:32 UTC, ionetek commented on src/features/components/header-menu/HeaderMenu.tsx
> +      <nav className='bg-transparent'>
Зачем bg-transparent? Элемент по-умолчанию прозрачный. 
Этот класс нужно использовать, если мы хотим переопределить фон блока имеющего какой-то цвет заливки.

2022-08-15 08:32 UTC, ionetek commented on src/pages/login/Login.tsx
> +              sign in
Давай внутри кнопок использовать написание с большой буквы. Sign in. Uppercase делать не нужно

2022-08-15 08:32 UTC, ionetek commented on src/pages/registration/Registration.tsx
>              </Link>
I have an account (uppercase убрать)

2022-08-15 08:32 UTC, ionetek commented on src/pages/tables/Tables.tsx
> +                <img className='h-4 inline' src={Arrow} alt='user photo' />
Player

2022-08-15 08:32 UTC, ionetek commented on src/pages/tables/Tables.tsx
> +                <img className='h-4 inline' src={Arrow} alt='user photo' />
Win

2022-08-15 08:32 UTC, ionetek commented on src/pages/tables/tablesList/TablesList.tsx
> +
.svg

2022-08-15 08:32 UTC, ionetek commented on src/pages/tables/tablesList/TablesList.tsx
> +  id?: number
Почему id не обязателен?

2022-08-15 08:32 UTC, ionetek commented on src/pages/tables/tablesList/TablesList.tsx
> +            table name
Пишем фразы с большой буквы

2022-08-15 08:32 UTC, ionetek commented on tailwind.config.js
>      extend: {
Зачем переопределила sm, md, lg, xl?

2022-08-15 12:49 UTC, kxnkxv approved these changes

2022-08-15 12:49 UTC, kxnkxv commented on src/pages/tables/Tables.tsx
> +            <TablesList tables={undefined}></TablesList>
Лучше null использовать вместо undefined

2022-08-15 12:49 UTC, kxnkxv commented on src/pages/tables/Tables.tsx
> +              <th></th>
Пустой блок можно схлопнуть до:
```suggestion
              <th />
```

2022-08-15 12:49 UTC, kxnkxv commented on src/pages/tables/Tables.tsx
> +              <td></td>
Пустой блок

2022-08-15 12:49 UTC, kxnkxv commented on src/pages/tables/Tables.tsx
> +              <td></td>
Пустой блок

2022-08-15 12:49 UTC, kxnkxv commented on src/pages/tables/tablesList/TablesList.tsx
> +          <th></th>
Пустой блок

2022-08-15 13:04 UTC, kxnkxv approved these changes

2022-08-16 06:03 UTC, ionetek approved these changes
Посмотрел. Рекомендации учла. Спасибо! 
Немедленно начинаю мердж)

2022-08-17 07:08 UTC, merged