fullscreen
AIG-GAMING/Poker pull request #57
Opened 2022-09-14 06:53 UTC by Gulnazmd

2022-09-14 12:35 UTC, ionetek requested changes
Нужно поправить фон

2022-09-14 12:35 UTC, ionetek commented on frontend/src/components/header/Header.tsx
> +  useEffect(() => {
setIsFullScreen

2022-09-14 16:11 UTC, kxnkxv approved these changes

2022-09-16 06:00 UTC, Gulnazmd commented on frontend/src/components/header/Header.tsx
> +  })
"если ты начнешь перемещаться по страницам, то у тебя isFullScreen будет всегда сбрасываться." - Я проверяла много раз, все работало корректно. Но сейчас переделала как ты посоветовал) Спасибо!

2022-09-16 06:09 UTC, ionetek approved these changes
Гульназ, PR аппрувнул. 
Оставил 1 коммент, что можно улучшить.

2022-09-16 06:09 UTC, ionetek commented on frontend/src/components/header/Header.tsx
>                <img src={FullScreen} className='h-6 sm:h-9' alt='FullScreen' />
Можно сократить до: **onClick={ toggleFullScreen }**
Поскольку не прокидываем аргументы в toggleFullScreen

2022-09-16 06:18 UTC, merged