49 processing error doctored components in react
AIG-GAMING/Poker pull request #59
Opened 2022-09-14 17:49 UTC by safari026

2022-09-15 07:28 UTC, Gulnazmd approved these changes

2022-09-16 06:20 UTC, ionetek requested changes

2022-09-16 06:20 UTC, ionetek commented on frontend/src/components/error-boundary/ErrorBoundary.tsx
> +  return (
Типы выносим в отдельный файл types.ts в папке компонента

2022-09-16 06:20 UTC, ionetek commented on frontend/src/components/error-boundary/ErrorBoundary.tsx
> +      ) : null}
Можно так:
```jsx
{ error?.stack && (
        <pre>
          {error?.message || null}
          {'\n\n'}
          {error?.stack}
        </pre>
      )}
```

2022-09-17 22:39 UTC, kxnkxv approved these changes

2022-09-19 10:43 UTC, merged