login, registration, router 6v
AIG-GAMING/Poker pull request #6
Opened 2022-08-05 16:12 UTC by Gulnazmd

2022-08-05 16:37 UTC, ionetek requested changes
Посмотрел. Кое-что нужно поправить в основном по стилям. Также у тебя, вероятно, не подключен pretier в IDE. Анатолий сделал конфигурацию, ее нужно подтянуть. Заметил, поскольку при использовании pretier удаляются " ; ", а у тебя они присутствуют.

В остальном все супер
Анатолий оставил комментарии:
В целом не плохо обрати внимание на комментарии. Со стилями надо цвета в отдельный файл занести (variables.css). И по типизации поправить. В целом все супер

2022-08-05 16:37 UTC, ionetek commented on src/features/ui/button/Button.tsx
> +import '../ui.css';
Под каждый компонент нужно создать свой css файл. В папке button - Button.module.css
(Вообще все подключаемые к компонентам css файлы должны лежать в тех же папках и иметь расширение .module.css)

2022-08-05 16:37 UTC, ionetek commented on src/features/ui/ui.css
> +  width: 320px;
Лучше не указывать жестко ширину для кнопок и инпутов. Они могут меняться. Параметры ширины мы будем накидывать из tailwind

2022-08-05 16:37 UTC, ionetek commented on src/styles/Style.css
> +  font-family: "Roboto Condensed";
Не увидел подключения Roboto

2022-08-05 18:46 UTC, Gulnazmd commented on src/features/ui/button/Button.tsx
> +import '../ui.css';
webpack не подгружает module.css

2022-08-05 18:48 UTC, ionetek commented on src/features/ui/button/Button.tsx
> +import '../ui.css';
Странно. Оставим css тогда

2022-08-05 19:10 UTC, Gulnazmd commented on src/styles/Style.css
> +  font-family: "Roboto Condensed";
done

2022-08-05 20:23 UTC, safari026 commented on src/features/ui/button/Button.css
> +  color: white;
Коллеги цвета в  папку style в файл variables

2022-08-05 20:25 UTC, Gulnazmd commented
Okay!

On Fri, 5 Aug 2022, 23:23 Anatoliy_Zhila, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/features/ui/button/Button.css
> <https://github.com/AIG-GAMING/Poker/pull/6#discussion_r939202675>:
>
> > @@ -0,0 +1,12 @@
>
> +.button {
>
> +  height: 40px;
>
> +  background: #be2e2e;
>
> +  border-radius: 8px;
>
> +  flex: none;
>
> +  order: 4;
>
> +  flex-grow: 0;
>
> +  color: white;
>
>
> Коллеги цвета в папку style в файл variables
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AIG-GAMING/Poker/pull/6#pullrequestreview-1063914360>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQPSW6MNVQLJOIO5HEJCVYDVXVZ3PANCNFSM55WST3WQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-05 20:26 UTC, safari026 commented on src/styles/Style.css
> +/* roboto-condensed-regular - latin_cyrillic */
имя файла со стилями с маленькой буквы мне кажется

2022-08-05 20:31 UTC, safari026 commented on src/features/ui/modal/Modal.tsx
> +const Modal: React.FunctionComponent<IPopupPageProps> = (props) => {
Можно полное имя не писать, а писать вот так FC<TProps>

2022-08-05 20:34 UTC, safari026 commented on src/pages/login/Login.tsx
> +  clicked: () => {}
жедательно типизацию функций которе ничего не возвращают вот так писать clicked:()=>void

2022-08-05 20:35 UTC, safari026 commented on src/pages/registration/Registration.tsx
> +  clicked: () => { void: any }
Здесь тоже самое. clicked:()=>void

2022-08-05 20:37 UTC, safari026 commented on src/pages/registration/Registration.tsx
> +import '../../styles/Style.css'
Лучше стили для формы сделать в этом файле, а не общем, так будет сохраняться архитектура

2022-08-05 20:38 UTC, Gulnazmd commented on src/pages/login/Login.tsx
> +  clicked: () => {}
Вот это хотела спросить, спасибо! Завтра исправлю всё

2022-08-05 20:49 UTC, safari026 commented on src/styles/Style.css
> +  color: #ffffff;
цвета в variables  file перенсти желательно

2022-08-06 06:24 UTC, merged

2022-08-06 06:24 UTC, Gulnazmd commented on src/styles/Style.css
> +  color: #ffffff;
Исправила. Спасибо за review!