Music
AIG-GAMING/Poker pull request #60
Opened 2022-09-15 07:25 UTC by Gulnazmd

2022-09-15 15:01 UTC, ionetek requested changes

2022-09-15 15:01 UTC, ionetek commented on frontend/src/pages/table/TableController.ts
> +          this.melody = new Audio(chips)
new Audio нужно вынести за пределы коллбэков. 
При таком написании, как сейчас они будут постоянно пересоздаваться.
Вынести можно в конструктор или вообще за пределы класса

2022-09-17 22:39 UTC, kxnkxv approved these changes

2022-09-19 13:29 UTC, ionetek approved these changes

2022-09-19 16:20 UTC, merged