Setting auth and registration
AIG-GAMING/Poker pull request #65
Opened 2022-09-28 02:39 UTC by safari026

2022-09-28 02:46 UTC, safari026 commented
Всем привет!!!
✅Сделал авторизацию и регестрацию по access and refresh token
✅Добавил паттер MVC
✅Сделал endpoint login registration refreshToken getUserOne
✅Добавил prisma postgres typescript
✅Запуск ws и роутинга на одном порту
✅AutWiddleware errorWiddleware
✅Протестировалв prisma
✅Добовил модель User и  Tkens  для базы данных и подключил

2022-09-29 09:13 UTC, ionetek requested changes
Оставил ряд комментариев.
+ хорошо бы в readme описать как работать с prism

2022-09-29 09:13 UTC, ionetek commented on frontend/README.md
> +Project will be available at http://localhost:3000
в нашем README.md следует вынести на уровень вверх или создать 2 файла для фронта и бэка в соответствующих папках

2022-09-30 17:57 UTC, safari026 commented on backend/src/app.ts
Это нужно для того чтобы webSocket  и роут запускались на одном порту.  За пример сожно глянуть эту статью https://stackoverflow.com/questions/22429744/how-to-setup-route-for-websocket-server-in-express
либо эту https://habr.com/ru/company/timeweb/blog/655143/
либо вот  https://stackoverflow.com/questions/64877154/how-can-i-connect-same-port-on-expressjs-and-socket-io

2022-09-30 17:58 UTC, safari026 commented on backend/src/app.ts
> +  logger.success(`Server started on port ${process.env.PORT}`)
Она не нужна типы сами подтягиваются автаматом типизация излишне

2022-10-03 06:23 UTC, Gulnazmd approved these changes

2022-10-03 16:48 UTC, ionetek approved these changes

2022-10-03 18:14 UTC, kxnkxv approved these changes

2022-10-04 10:25 UTC, merged